# Project information
site_name: GPT3 Framework
site_description: Simple Framework to Use GPT3 in an Easy and Fast Manner
site_author: Ramit Surana
site_url: https://ramitsurana.github.io/gpt3-framework/

# Repository
repo_name: ramitsurana/gpt3-framework
repo_url: https://github.com/ramitsurana/gpt3-framework/

# Copyright
copyright: Copyright &copy; 2021 Ramit Surana

# Configuration
theme:
  name: material
  language: en
  features:
    - tabs
    - instant
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/microsoft-xbox
    repo: material/microsoft-xbox

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ramitsurana
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ramitsurana
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ramitsurana

# Google Analytics
google_analytics:
  - UA-71344758-5
  - auto

nav:
  - Home: README.md
  - Engines: engines/engines.md
  - Applications: applications/applications.md
  - Deployment: deployment/deployment.md

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search # necessary for search to work