name: GPT3 Framework Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Mkdocs
      run: |
        sudo apt-get update -y
        sudo apt-get install -y mkdocs
    - name: Deploy on gh-pages
      run: |
        git fetch --all
        git fetch origin gh-pages:gh-pages
        mkdocs gh-deploy
